  name: be-harvester CI

  on:
    pull_request:
      branches:
      - sandbox
      - aztec
    push:
      branches:
      - sandbox
      - aztec

  env:
    AWS_REPOSITORY_URL_AZTEC: 033160085112.dkr.ecr.ap-south-1.amazonaws.com/aztec-be-harvester:latest
    AWS_REPOSITORY_URL_MAYA: ${{ secrets.AWS_REPOSITORY_URL_MAYA }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  jobs:
    build-and-push-aztec:
      if: github.ref == 'refs/heads/aztec'
      name: Build and push image to AWS ECR for AZTEC region
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_REPOSITORY_URL_AZTEC

      - name: Build and tag the image
        run: docker build -t $AWS_REPOSITORY_URL_AZTEC .

      - name: Push
        run: docker push $AWS_REPOSITORY_URL_AZTEC
    build-and-push-maya:
      if: github.ref == 'refs/heads/sandbox'
      name: Build and push image to AWS ECR for MAYA region
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Setup ECR
          run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_REPOSITORY_URL_MAYA

        - name: Build and tag the image
          run: docker build -t $AWS_REPOSITORY_URL_MAYA .

        - name: Push
          run: docker push $AWS_REPOSITORY_URL_MAYA
